packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@lezer/common": ^1.5.1
  "@lezer/markdown": ^1.6.3
  "@napi-rs/canvas": ^0.1.97
  "@playwright/test": ^1.59.1
  "@types/node": ^25
  jiti: ^2.6.1
  typescript: ^6
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogMode: prefer

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
